proc Randomize(int $num, int $range)
{
    string $sels[] = `ls -sl`;
    
    for($i=0; $i<size($sels); $i++)
    {
        for($j=0; $j<$num; $j++)
        {
            float $xPos = `rand (-$range) $range`;
            float $yPos = `rand (-$range) $range`;
            float $zPos = `rand (-$range) $range`;
            
            string $obj[] =`duplicate -rr $sels[$i]`;
            move $xPos $yPos $zPos $obj[0];
        }
    }
}

Randomize(10, 100);